# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fb543e27f2c7b852a885def47071299cc9e36a133c44e05f136677bec0fd48742006a02346022299f7ff7e67d7015516bcd26c28d6729ec22b71920d352bb77

test:
  secret_key_base: 6b534f13bcb9ad29f2b9a572c1dc1a424569931bb8c3ef436b252543ca904a09f41c51c634ac2122f826ca1bf1fb34b39902416cb6a1b920dea71c28ef8341dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
